In [22]:
import os
import numpy as np
import pandas as pd
from PIL import Image
import keras 
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Dropout, InputLayer
from tensorflow.keras.models import Sequential, Model, load_model

In [23]:
directory_path = r'D:\LUNA16\classsification'

In [24]:
images = []
image_labels = []
image_height = 48
image_width = 48

In [25]:
train_df = pd.read_csv('D:\LUNA16\classsification\Train.csv')

In [26]:
for index in range(train_df.shape[0]):
        data = train_df.iloc[:, :].values
        np.random.shuffle(data)
    # For Image
        images = data[:, 1:]
    # For Labels
        labels = data[:, 0]

In [27]:
import numpy as np
from matplotlib import pyplot as plt
import matplotlib
import glob
import PIL
from PIL import Image
import glob
image=[]
for filename in images:
    print(filename)
    for i in filename:
        print(i)
        print(type(i))
        img_array = np.load(i, allow_pickle=True)
        img_array=img_array.reshape(192,192,3)
        image.append(img_array)

['D:\\LUNA16\\classsification\\aug2/aug132_5.npy']
D:\LUNA16\classsification\aug2/aug132_5.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug102_7.npy']
D:\LUNA16\classsification\aug2/aug102_7.npy
<class 'str'>
['D:\\LUNA16\\classsification\\0/0_10_423.npy']
D:\LUNA16\classsification\0/0_10_423.npy
<class 'str'>
['D:\\LUNA16\\classsification\\0/0_10_168.npy']
D:\LUNA16\classsification\0/0_10_168.npy
<class 'str'>
['D:\\LUNA16\\classsification\\0/0_10_307.npy']
D:\LUNA16\classsification\0/0_10_307.npy
<class 'str'>
['D:\\LUNA16\\classsification\\0/0_10_851.npy']
D:\LUNA16\classsification\0/0_10_851.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug121_6.npy']
D:\LUNA16\classsification\aug2/aug121_6.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug109_2.npy']
D:\LUNA16\classsification\aug2/aug109_2.npy
<class 'str'>
['D:\\LUNA16\\classsification\\0/0_10_74.npy']
D:\LUNA16\classsification\0/0_10_74.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug123_2.npy']


In [28]:
print(type(labels))

<class 'numpy.ndarray'>


In [29]:
print(image[0])

[[[11.7459383  19.81031227 19.81031227]
  [19.81031227 18.40781212 18.40781212]
  [26.64750099 26.64750099 12.62250042]
  ...
  [ 5.2593751   5.96062469  3.68156242]
  [ 6.48656273 12.62250042 11.7459383 ]
  [11.7459383  12.79781246 12.27187538]]

 [[17.35593796 17.35593796 10.51875019]
  [10.51875019 11.7459383  12.44718838]
  [19.45968628 19.45968628 14.90156269]
  ...
  [11.22000027 11.22000027  7.36312485]
  [ 8.940938   10.16812515  8.590312  ]
  [ 9.46687508 10.34343719 13.67437458]]

 [[ 8.590312    8.590312   13.3237505 ]
  [13.3237505   9.29156208  9.29156208]
  [44.52937698 44.52937698 16.12874985]
  ...
  [ 4.20749998  4.20749998  7.88906288]
  [ 7.53843784  7.53843784  7.18781281]
  [ 6.66187525  6.66187525 10.16812515]]

 ...

 [[17.88187599 17.88187599 19.63500023]
  [23.14125061 20.16093826 18.05718803]
  [14.02500057 12.97312546  9.29156208]
  ...
  [39.09468842 39.09468842 30.32906342]
  [30.32906342 32.95875168 32.95875168]
  [22.26468849 22.26468849 26.47218704]]

 [

In [30]:
img = np.array(image)
image_labels = np.array(labels)

In [11]:
print(img[0])

[[[219.49125671 219.49125671 226.50376892]
  [226.50376892 226.50376892 236.14595032]
  [225.62719727 228.78282166 228.78282166]
  ...
  [ 30.15375137  17.88187599  18.40781212]
  [ 18.40781212  24.89437675  18.58312416]
  [ 23.14125061  30.15375137  16.82999992]]

 [[177.76687622 177.76687622 164.61843872]
  [164.61843872 216.68626404 216.68626404]
  [216.68626404 211.25157166 211.25157166]
  ...
  [  0.           0.          29.27718925]
  [167.94937134 189.33750916 182.50032043]
  [178.11750793 241.58062744 260.51437378]]

 [[ 32.60812378   3.50625014  11.39531231]
  [ 11.39531231  27.69937515  27.69937515]
  [ 18.05718803  18.05718803  18.05718803]
  ...
  [191.79187012 185.30532837 224.40000916]
  [248.06719971 240.00280762 235.26939392]
  [227.0296936  230.01000977 234.56813049]]

 ...

 [[ 38.04281235  36.99093628   0.        ]
  [ 11.7459383   24.54375076  24.54375076]
  [ 29.97843742  15.07687569  20.86218834]
  ...
  [  5.96062469   5.96062469  40.84781647]
  [ 40.84781647  4

In [31]:

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(img, image_labels, test_size=0.2)

In [35]:

# Normalising the data
X_train = X_train/255.0
X_val = X_val/255.0

MemoryError: Unable to allocate 3.46 GiB for an array with shape (4198, 192, 192, 3) and data type float64

In [14]:
from tensorflow.keras.applications import vgg16

In [15]:
vgg16_model = vgg16.VGG16(weights = "imagenet", include_top = False, input_shape=(192,192,3))

In [16]:
for layer in vgg16_model.layers:
    layer.trainable = False  

In [17]:
vgg16_model.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 192, 192, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 192, 192, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 192, 192, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 96, 96, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 96, 96, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 96, 96, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 48, 48, 128)       0     

In [18]:
x = vgg16_model.output
x = Flatten()(x)
x = Dense(units = 512, activation = "relu")(x)
x = Dropout(rate = 0.25)(x)
x = Dense(units = 256, activation = "relu")(x)
output = Dense(units = 43, activation = "softmax")(x)

In [19]:
vgg16_modified_model = Model(inputs = vgg16_model.input, outputs = output)

In [20]:
vgg16_modified_model.compile(
    optimizer="Adam",
    loss = "sparse_categorical_crossentropy",
    metrics = ["accuracy"]
)

In [21]:
vgg16_modified_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 192, 192, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 192, 192, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 192, 192, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 96, 96, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 96, 96, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 96, 96, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 48, 48, 128)       0     

In [36]:
X_train = np.asarray(X_train).astype(np.float32)
y_train = np.asarray(y_train).astype(np.int32)
X_val = np.asarray(X_val).astype(np.float32)
y_val = np.asarray(y_val).astype(np.int32)

In [23]:
epochs = 20
history = vgg16_modified_model.fit(X_train, y_train, validation_data=(X_val, y_val),epochs = epochs, batch_size = 32)

Epoch 1/20
132/132 [==============================] - 450s 3s/step - loss: 0.8878 - accuracy: 0.6293 - val_loss: 0.5283 - val_accuracy: 0.7381
Epoch 2/20
132/132 [==============================] - 444s 3s/step - loss: 0.5117 - accuracy: 0.7487 - val_loss: 0.4522 - val_accuracy: 0.8057
Epoch 3/20
132/132 [==============================] - 442s 3s/step - loss: 0.4404 - accuracy: 0.7968 - val_loss: 0.5654 - val_accuracy: 0.7314
Epoch 4/20
132/132 [==============================] - 1037s 8s/step - loss: 0.4321 - accuracy: 0.8006 - val_loss: 0.5607 - val_accuracy: 0.7295
Epoch 5/20
132/132 [==============================] - 439s 3s/step - loss: 0.3712 - accuracy: 0.8280 - val_loss: 0.4095 - val_accuracy: 0.8057
Epoch 6/20
132/132 [==============================] - 441s 3s/step - loss: 0.3201 - accuracy: 0.8611 - val_loss: 0.3614 - val_accuracy: 0.8438
Epoch 7/20
132/132 [==============================] - 440s 3s/step - loss: 0.3223 - accuracy: 0.8556 - val_loss: 0.4890 - val_accuracy: 0.780

In [24]:
vgg16_modified_model.save("VGG16new2.h5")

In [5]:
test_df = pd.read_csv('D:\LUNA16\classsification\Test2.csv')

In [6]:
for index in range(test_df.shape[0]):
        data = test_df.iloc[:, :].values
        np.random.shuffle(data)
    # For Image
        fig = data[:, 1:]
    # For Labels
        num = data[:, 0]

In [7]:
fig1=[]
for filename in fig:
    print(filename)
    for i in filename:
        print(i)
        print(type(i))
        img_array = np.load(i, allow_pickle=True)
        img_array=img_array.reshape(192,192,3)
        fig1.append(img_array)

['D:\\LUNA16\\classsification\\0/0_0_187.npy']
D:\LUNA16\classsification\0/0_0_187.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug106_19.npy']
D:\LUNA16\classsification\aug2/aug106_19.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug109_15.npy']
D:\LUNA16\classsification\aug2/aug109_15.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug100_3.npy']
D:\LUNA16\classsification\aug2/aug100_3.npy
<class 'str'>
['D:\\LUNA16\\classsification\\0/0_0_200.npy']
D:\LUNA16\classsification\0/0_0_200.npy
<class 'str'>
['D:\\LUNA16\\classsification\\1/2_57_274.npy']
D:\LUNA16\classsification\1/2_57_274.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug100_13.npy']
D:\LUNA16\classsification\aug2/aug100_13.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug106_2.npy']
D:\LUNA16\classsification\aug2/aug106_2.npy
<class 'str'>
['D:\\LUNA16\\classsification\\aug2/aug101_15.npy']
D:\LUNA16\classsification\aug2/aug101_15.npy
<class 'str'>
['D:\\LUNA16\\classsification\\0/

In [8]:
X_test = np.array(fig1)

In [9]:
X_test = X_test/255.0

In [10]:
X_test = np.asarray(X_test).astype(np.float32)
from keras.models import load_model
model=load_model("VGG16new2.h5")

In [11]:
y_pred1 = np.argmax(model.predict(X_test), axis=1)

In [12]:
print(y_pred1)

[0 1 1 1 0 1 0 1 1 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0
 0 1 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0 0 1 1 0 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0 0
 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 0 1 0 0 0
 0 0 1 0 0 1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1
 0 1 1 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 1 0 1 1 0 0 0
 1 1 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0
 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0
 1 1 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 0 1
 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 1 0 0
 1 0 1 0 1 0 1 0 0 1 1 1 0 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 0 0 1 1 0 1 1 0 0
 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 1 1]


In [13]:
y_test1=num.astype('int64')

In [14]:
y_test1.dtype

dtype('int64')

In [18]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
print("Accuracy Score:")
print(accuracy_score(y_pred1, y_test1) *100)
print(classification_report(y_pred1, y_test1))

Accuracy Score:
89.84198645598194
              precision    recall  f1-score   support

           0       1.00      0.83      0.90       257
           1       0.81      0.99      0.89       186

    accuracy                           0.90       443
   macro avg       0.90      0.91      0.90       443
weighted avg       0.92      0.90      0.90       443



In [21]:
import tensorflow as tf
import keras_efficientnet_v2
model = keras_efficientnet_v2.EfficientNetV2L(pretrained="imagenet21k-ft1k",input_shape=(192, 192, 3))

>>>> Load pretrained from: C:\Users\dillu\.keras\models/efficientnetv2\efficientnetv2-l-21k-ft1k.h5


In [37]:
model.summary()

Model: "EfficientNetV2L"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 192, 192, 3  0           []                               
                                )]                                                                
                                                                                                  
 stem_conv (Conv2D)             (None, 96, 96, 32)   864         ['input_1[0][0]']                
                                                                                                  
 stem_bn (BatchNormalization)   (None, 96, 96, 32)   128         ['stem_conv[0][0]']              
                                                                                                  
 stem_swish (Activation)        (None, 96, 96, 32)   0           ['stem_bn[0][0]']  

In [38]:
x = model.output
from tensorflow.keras.layers import Dense
output = Dense(units = 43, activation = "sigmoid")(x)

In [39]:
EFV_model = tf.keras.Model(inputs=model.input, outputs=[model.output, output])

In [40]:
EFV_model.compile(
    optimizer="Adam",
    loss = "sparse_categorical_crossentropy",
    metrics = ["accuracy"]
)

In [41]:
EFV_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 192, 192, 3  0           []                               
                                )]                                                                
                                                                                                  
 stem_conv (Conv2D)             (None, 96, 96, 32)   864         ['input_1[0][0]']                
                                                                                                  
 stem_bn (BatchNormalization)   (None, 96, 96, 32)   128         ['stem_conv[0][0]']              
                                                                                                  
 stem_swish (Activation)        (None, 96, 96, 32)   0           ['stem_bn[0][0]']            

In [2]:
epochs = 10
history = EFV_model.fit(X_train, y_train, validation_data=(X_val, y_val),epochs = epochs, batch_size = 64)

NameError: name 'EFV_model' is not defined